name: Build Atlantis

on: workflow_dispatch


env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  build:
    needs: lint
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Container
        run: |
          ./build.sh
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Release
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUT_ID }}
        run: |
          echo "This: ${AWS_ACCOUNT_ID}"
          ./release.sh ${AWS_ACCOUNT_ID}
