name: Build Atlantis

on: workflow_dispatch


env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  build:
    needs: lint
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Container
        run: |
          ./build.sh
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::608911059386:role/test_oidc_role
          role-session-name: Mysession
      - name: upload image to ECR
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          repo: atlantis
          region: us-east-1
          create_repo: false
      # - name: Login to aws ECR
      #   id: ecr-login
      #   uses: thalevon/ecr-login@master
      #   with:
      #     args: 'get-login --no-inclued-email --region ${AWS_DEFAULT_REGION}'
      # - name: docker login
      #   run: ${{ steps.ecr-login.outputs.login-string }}
      # - name: Release
      #   run: |
      #     echo "This: 608911059386"
      #     ./release.sh 608911059386

